### ISSUE TITLE
感谢楼主，正在用，感觉还不错

### ISSUE THREAD

**Issue by mianhk** [yuquewebclipper/yuque-web-clipper#2]
不过网页剪藏好像效果暂时还不是太好，可以参考一下Evernote之类的嘛

**Comment by DiamondYuan** [comment]
> 不过网页剪藏好像效果暂时还不是太好，可以参考一下Evernote之类的嘛

其实 UI 我是参考 Evernote 的。请问哪方面效果不好？

**Comment by mianhk** [comment]
网页剪藏，整个页面的时候排版好像会乱，不过我主要是存的链接比较多

**Comment by DiamondYuan** [comment]
大多数情况下只需要智能提取提取整个网站的主要内容就可以了。
Evernote 底层的数据格式是类似于 html 的文档，而不是 markdown。
语雀储存的全部都是 markdown。会把网页转成markdown再储存，所以页面排版有时候会乱。


未来可能会写一个 手动匹配模式，用户可以根据自定义的 css 选择权来筛选需要的内容。

**Comment by myzcid** [comment]
我感觉为知原生的网页收藏排版是最好的
