### ISSUE TITLE
配置AccessToken出现问题

### ISSUE THREAD

**Issue by tankle** [yuquewebclipper/yuque-web-clipper#21]
无法访问到AccessToken或者域名出现问题，我配置的域名是：www.yuque.com

**Comment by DiamondYuan** [comment]
请问你使用的是哪个版本？无论是哪个版本都有默认的域名，不需要自己配置。

**Comment by tankle** [comment]
chrome 扩展程序0.0.9

**Comment by DiamondYuan** [comment]
@tankle  直接输入token就可以了。我刚才试了一下没问题。

**Comment by DiamondYuan** [comment]
我先关闭了，有问题可以重新打开。
