### ISSUE TITLE
通过插件剪藏的文章无法搜索

### ISSUE THREAD

**Issue by zhiyue** [yuquewebclipper/yuque-web-clipper#22]
如题，通过插件剪藏的文章无法在语雀云上搜索。需要编辑文章，然后更新才能够检索
![image](https://user-images.githubusercontent.com/4208883/52843507-51674800-313d-11e9-9193-e18a356da90f.png)
![image](https://user-images.githubusercontent.com/4208883/52843556-6e038000-313d-11e9-985d-c1a984ec269b.png)
然后编辑并且更新

![image](https://user-images.githubusercontent.com/4208883/52843653-b458df00-313d-11e9-8eda-8a067b7f6c7d.png)

如果是 api 的问题。我估计应该提 bug 给语雀云。
我会在稍后尝试阅读相关的 api 文档

**Comment by DiamondYuan** [comment]
这个是语雀的问题，等待语雀修复吧。
语雀的文档分为新版本和旧版本，通过API创建的文档都是旧版本的。
