### ISSUE TITLE
希望可以选择团队内知识库

### ISSUE THREAD

**Issue by freedomelf** [yuquewebclipper/yuque-web-clipper#99]
创建账户时应该可以选择个人还是团队，选择团队后再加载默认的知识库

**Comment by DiamondYuan** [comment]
你指的是是否显示团队知识库么？

**Comment by DiamondYuan** [comment]
这个简单，下一个版本会加上。

**Comment by DiamondYuan** [comment]
@freedomelf 

![image](https://user-images.githubusercontent.com/9692408/56667487-7f8a7a80-66e0-11e9-8ec5-1d92515d309c.png)

**Comment by freedomelf** [comment]
nice，我去试试

**Comment by DiamondYuan** [comment]
> nice，我去试试

还没提交

**Comment by DiamondYuan** [comment]
> nice，我去试试

ok 了。下载最新版本。
